"""ORM model for root_cause_reports table (Sprint 5 - Task 41).

Stores complete AI root cause analysis reports generated by IBM Bob 2.0.
"""

from __future__ import annotations

from datetime import datetime
import enum
from typing import TYPE_CHECKING, Any
import uuid

from sqlalchemy import DateTime, Enum, ForeignKey, Integer, String, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.root_cause_evidence import RootCauseEvidence


class ConfidenceLevel(enum.StrEnum):
    """Deterministic confidence rating bands."""

    VERY_HIGH = "VERY_HIGH"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class AnalysisStatus(enum.StrEnum):
    """Lifecycle status of AI analysis."""

    PENDING = "PENDING"
    ANALYZING = "ANALYZING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class RootCauseReport(Base):
    """Persisted AI root cause diagnostic report."""

    __tablename__ = "root_cause_reports"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )
    comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("behavior_comparisons.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    repository_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        index=True,
    )
    base_commit: Mapped[str] = mapped_column(String(64), nullable=False)
    head_commit: Mapped[str] = mapped_column(String(64), nullable=False)
    status: Mapped[AnalysisStatus] = mapped_column(
        Enum(
            AnalysisStatus,
            name="analysisstatus",
            create_constraint=True,
        ),
        default=AnalysisStatus.COMPLETED,
        nullable=False,
        index=True,
    )
    summary: Mapped[str] = mapped_column(String, nullable=False)
    confidence_score: Mapped[int] = mapped_column(Integer, nullable=False)
    confidence_band: Mapped[ConfidenceLevel] = mapped_column(
        Enum(
            ConfidenceLevel,
            name="confidence_level",
            create_constraint=True,
        ),
        nullable=False,
    )
    primary_candidate: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
    )
    secondary_candidates: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
    )
    repair_plan: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
    )
    explanation: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
    )
    bob_prompt: Mapped[str] = mapped_column(
        String,
        nullable=False,
        default="",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        nullable=False,
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    evidence_records: Mapped[list[RootCauseEvidence]] = relationship(
        "RootCauseEvidence",
        back_populates="report",
        cascade="all, delete-orphan",
        lazy="selectin",
    )
