import {
  RepositoryState,
  RuntimeExecution,
  BehaviorComparisonSummary,
  RootCauseReport,
  RepairReportData,
} from '../types'

export const mockRepository: RepositoryState = {
  url: 'https://github.com/BP1202/SceneDiff.git',
  name: 'BP1202/SceneDiff',
  defaultBranch: 'main',
  baseCommit: {
    sha: 'f4a180d297a1b38f8216c59b2ec4ef36894da071',
    shortSha: 'f4a180d',
    author: 'Bhoomi Patel',
    message: 'feat(auth): initial JWT validation and login session',
    timestamp: '2026-09-26 14:20:10 UTC',
    branch: 'main',
    filesChanged: 3,
    insertions: 48,
    deletions: 12,
  },
  headCommit: {
    sha: 'e93b11c841b9c52fe156321ad1045239a9c9f42d',
    shortSha: 'e93b11c',
    author: 'Bhoomi Patel',
    message: 'refactor(auth): simplify token decoder without null guard',
    timestamp: '2026-09-27 09:12:45 UTC',
    branch: 'dev',
    filesChanged: 1,
    insertions: 2,
    deletions: 6,
  },
  availableBranches: ['main', 'dev', 'feat/repair-engine', 'feat/frontend-workspace'],
  recentCommits: [
    {
      sha: 'e93b11c841b9c52fe156321ad1045239a9c9f42d',
      shortSha: 'e93b11c',
      author: 'Bhoomi Patel',
      message: 'refactor(auth): simplify token decoder without null guard',
      timestamp: '2026-09-27 09:12:45 UTC',
      branch: 'dev',
    },
    {
      sha: 'f4a180d297a1b38f8216c59b2ec4ef36894da071',
      shortSha: 'f4a180d',
      author: 'Bhoomi Patel',
      message: 'feat(auth): initial JWT validation and login session',
      timestamp: '2026-09-26 14:20:10 UTC',
      branch: 'main',
    },
    {
      sha: 'a1b2c3d4e5f60718293a4b5c6d7e8f9012345678',
      shortSha: 'a1b2c3d',
      author: 'IBM Bob',
      message: 'feat(comparator): add DOM mutation tree analyzer',
      timestamp: '2026-09-25 18:30:00 UTC',
      branch: 'main',
    },
  ],
}

export const mockRuntimeExecution: RuntimeExecution = {
  id: 'rt-8219-c941',
  commitSha: 'e93b11c841b9c',
  status: 'completed',
  durationMs: 1420,
  domNodesCaptured: 342,
  networkRequestsCaptured: 19,
  consoleMessagesCaptured: 4,
  storageKeysCaptured: 7,
  logs: [
    { id: '1', timestamp: '00:00.012', level: 'info', message: 'Chromium headless instance spawned with Secret Shield', phase: 'browser' },
    { id: '2', timestamp: '00:00.280', level: 'info', message: 'Navigated to http://localhost:5173/login', phase: 'navigation' },
    { id: '3', timestamp: '00:00.640', level: 'debug', message: 'DOM tree snapshot normalized: 342 interactive nodes indexed', phase: 'dom' },
    { id: '4', timestamp: '00:00.910', level: 'warn', message: 'Network POST /api/v1/auth/login returned HTTP 500', phase: 'network' },
    { id: '5', timestamp: '00:01.120', level: 'error', message: 'Console Error: Uncaught TypeError: Cannot read properties of undefined (reading "role")', phase: 'console' },
    { id: '6', timestamp: '00:01.390', level: 'info', message: 'Session storage and cookies captured (auto-masked)', phase: 'storage' },
    { id: '7', timestamp: '00:01.420', level: 'info', message: 'Runtime trace collection completed successfully in 1,420ms', phase: 'complete' },
  ],
}

export const mockComparisonSummary: BehaviorComparisonSummary = {
  id: 'cmp-9142-b018',
  baseCommit: 'f4a180d',
  headCommit: 'e93b11c',
  divergenceStep: 3,
  totalDifferences: 8,
  severityCounts: {
    CRITICAL: 2,
    HIGH: 3,
    MEDIUM: 2,
    LOW: 1,
    INFO: 0,
  },
  timeline: [
    {
      id: 'evt-1',
      timestamp: '00:00.180',
      stepIndex: 1,
      category: 'dom',
      severity: 'LOW',
      title: 'Initial Viewport Mounted',
      description: 'Login form rendered with email/password input controls.',
      route: '/login',
      evidenceCount: 1,
    },
    {
      id: 'evt-2',
      timestamp: '00:00.450',
      stepIndex: 2,
      category: 'network',
      severity: 'INFO',
      title: 'Authentication Request Dispatched',
      description: 'POST /api/v1/auth/login dispatched with payload.',
      route: '/login',
      evidenceCount: 1,
    },
    {
      id: 'evt-3',
      timestamp: '00:00.910',
      stepIndex: 3,
      category: 'network',
      severity: 'CRITICAL',
      title: 'First Meaningful Runtime Divergence',
      description: 'Endpoint returned HTTP 500 (Internal Server Error). Base commit returned 200 OK.',
      route: '/api/v1/auth/login',
      evidenceCount: 4,
      isFirstDivergence: true,
      details: {
        baseStatus: 200,
        headStatus: 500,
        divergenceType: 'HTTP_STATUS_REGRESSION',
      },
    },
    {
      id: 'evt-4',
      timestamp: '00:01.120',
      stepIndex: 4,
      category: 'console',
      severity: 'HIGH',
      title: 'Uncaught TypeError in Browser Console',
      description: 'Uncaught TypeError: Cannot read properties of undefined (reading "role") at handleLoginResponse.',
      route: '/login',
      evidenceCount: 2,
    },
    {
      id: 'evt-5',
      timestamp: '00:01.240',
      stepIndex: 5,
      category: 'dom',
      severity: 'CRITICAL',
      title: 'Login Button Trapped in Loading State',
      description: 'Submit button remains disabled indefinitely. Expected redirect to /dashboard did not fire.',
      route: '/login',
      evidenceCount: 3,
    },
    {
      id: 'evt-6',
      timestamp: '00:01.320',
      stepIndex: 6,
      category: 'storage',
      severity: 'HIGH',
      title: 'Auth Token Missing in LocalStorage',
      description: 'Base commit saved bearer token. Head commit left localStorage empty due to failed auth.',
      route: '/login',
      evidenceCount: 1,
    },
  ],
  domDiffs: [
    {
      id: 'dom-1',
      selector: 'button#login-submit',
      changeType: 'attribute_changed',
      baseValue: 'class="btn-primary" (enabled)',
      headValue: 'class="btn-primary is-loading" disabled',
      xpath: '/html/body/div[1]/form/button',
      severity: 'CRITICAL',
    },
    {
      id: 'dom-2',
      selector: 'div.auth-error-banner',
      changeType: 'added',
      baseValue: '(none)',
      headValue: '<div class="alert-danger">Unexpected Server Error</div>',
      xpath: '/html/body/div[1]/div[2]',
      severity: 'HIGH',
    },
    {
      id: 'dom-3',
      selector: 'header.user-nav-profile',
      changeType: 'removed',
      baseValue: '<header class="user-nav-profile">Welcome, Bhoomi</header>',
      headValue: '(not rendered)',
      xpath: '/html/body/header',
      severity: 'HIGH',
    },
  ],
  networkDiffs: [
    {
      id: 'net-1',
      url: '/api/v1/auth/login',
      method: 'POST',
      baseStatus: 200,
      headStatus: 500,
      baseLatencyMs: 142,
      headLatencyMs: 620,
      severity: 'CRITICAL',
      isRegression: true,
      errorDetail: 'Internal Server Error: NoneType object has no attribute "role"',
    },
    {
      id: 'net-2',
      url: '/api/v1/users/me',
      method: 'GET',
      baseStatus: 200,
      headStatus: 0,
      baseLatencyMs: 85,
      headLatencyMs: 0,
      severity: 'HIGH',
      isRegression: true,
      errorDetail: 'Never invoked due to authentication failure upstream',
    },
    {
      id: 'net-3',
      url: '/api/v1/telemetry/heartbeat',
      method: 'GET',
      baseStatus: 200,
      headStatus: 200,
      baseLatencyMs: 34,
      headLatencyMs: 36,
      severity: 'LOW',
      isRegression: false,
    },
  ],
  consoleDiffs: [
    {
      id: 'con-1',
      type: 'error',
      message: 'Uncaught TypeError: Cannot read properties of undefined (reading "role")',
      stackTrace: 'at handleLoginResponse (auth.js:84:18)\n    at onSubmit (login.tsx:42:12)',
      occurrence: 'new',
      severity: 'HIGH',
    },
    {
      id: 'con-2',
      type: 'warn',
      message: 'Axios request failed with status code 500',
      occurrence: 'new',
      severity: 'MEDIUM',
    },
  ],
  storageDiffs: [
    {
      key: 'auth_token',
      storageType: 'localStorage',
      baseValue: 'eyJhbGciOiJIUzI1Ni...[REDACTED]',
      headValue: '(empty)',
      isSecretMasked: true,
      changeType: 'removed',
    },
    {
      key: 'session_id',
      storageType: 'sessionStorage',
      baseValue: 'sess_9941a82',
      headValue: '(empty)',
      isSecretMasked: true,
      changeType: 'removed',
    },
  ],
  performanceDiffs: [
    { metric: 'TTFB', unit: 'ms', baseValue: 120, headValue: 620, deltaPercent: 416.7, severity: 'HIGH' },
    { metric: 'FCP', unit: 'ms', baseValue: 310, headValue: 380, deltaPercent: 22.5, severity: 'LOW' },
    { metric: 'LCP', unit: 'ms', baseValue: 640, headValue: 1420, deltaPercent: 121.8, severity: 'HIGH' },
    { metric: 'DOM_Interactive', unit: 'ms', baseValue: 410, headValue: 510, deltaPercent: 24.3, severity: 'LOW' },
    { metric: 'JS_Heap', unit: 'MB', baseValue: 24.5, headValue: 26.2, deltaPercent: 6.9, severity: 'LOW' },
  ],
}

export const mockRootCauseReport: RootCauseReport = {
  id: 'rc-7182-d041',
  comparisonId: 'cmp-9142-b018',
  primaryCandidate: {
    file: 'app/auth/login.py',
    functionName: 'validate_token',
    lineStart: 24,
    lineEnd: 38,
    score: 0.94,
    rationale: 'Function returns None for expired or malformed tokens instead of raising AuthenticationError or returning valid payload dictionary.',
    isPrimary: true,
  },
  secondaryCandidates: [
    {
      file: 'app/api/v1/endpoints/auth.py',
      functionName: 'login_endpoint',
      lineStart: 45,
      lineEnd: 62,
      score: 0.72,
      rationale: 'Caller does not verify if validate_token() returns None before subscripting payload["role"].',
      isPrimary: false,
    },
  ],
  rootCauseConfidence: 94,
  repairConfidence: 88,
  explanation: 'In commit e93b11c, the defensive null guard in validate_token() was removed during payload decoder refactoring. When an expired token or null header is passed, validate_token() returns None. The calling endpoint immediately attempts payload["role"], raising an unhandled AttributeError that triggers HTTP 500 and crashes the frontend authentication state.',
  repairRecommendation: 'Add an explicit null guard in validate_token(). If the decoded payload is None or invalid, raise an AuthenticationError with a 401 status instead of returning None.',
  evidenceNodes: [
    { id: 'node-commit', label: 'Commit e93b11c', category: 'commit', description: 'Removed null check in auth/login.py' },
    { id: 'node-code', label: 'validate_token()', category: 'code', severity: 'CRITICAL', description: 'Returns None when token is invalid' },
    { id: 'node-net', label: 'POST /login (500)', category: 'network', severity: 'CRITICAL', description: 'HTTP 500 Internal Error' },
    { id: 'node-console', label: 'TypeError (role)', category: 'console', severity: 'HIGH', description: 'Uncaught TypeError in frontend' },
    { id: 'node-dom', label: 'Login Button Trapped', category: 'dom', severity: 'CRITICAL', description: 'Button stuck in loading state' },
    { id: 'node-storage', label: 'Empty Token', category: 'storage', severity: 'HIGH', description: 'Token never stored in localStorage' },
  ],
  evidenceEdges: [
    { id: 'e1', source: 'node-commit', target: 'node-code', relation: 'modified', weight: 1.0 },
    { id: 'e2', source: 'node-code', target: 'node-net', relation: 'causes 500 error in', weight: 0.95 },
    { id: 'e3', source: 'node-net', target: 'node-console', relation: 'triggers exception in', weight: 0.9 },
    { id: 'e4', source: 'node-console', target: 'node-dom', relation: 'blocks render of', weight: 0.88 },
    { id: 'e5', source: 'node-net', target: 'node-storage', relation: 'prevents storage in', weight: 0.85 },
  ],
  createdAt: '2026-09-27T09:14:00Z',
}

export const mockRepairReport: RepairReportData = {
  id: 'rep-4491-a882',
  rootCauseId: 'rc-7182-d041',
  comparisonId: 'cmp-9142-b018',
  summary: 'Fix validate_token null return and raise AuthenticationError',
  targetFile: 'app/auth/login.py',
  targetFunction: 'validate_token',
  patchContent: `--- a/app/auth/login.py
+++ b/app/auth/login.py
@@ -28,7 +28,11 @@ def validate_token(token: str) -> dict:
     try:
         payload = jwt.decode(token, SECRET_KEY, algorithms=["HS256"])
-        return payload
+        if payload is None:
+            raise AuthenticationError("Token payload evaluated to null")
+        return payload
     except jwt.PyJWTError as exc:
-        return None
+        raise AuthenticationError(f"Invalid token signature: {exc}") from exc
`,
  planActions: [
    { step: 1, description: 'Inspect validate_token() signature and return contract', actionType: 'inspect' },
    { step: 2, description: 'Add defensive null guard after jwt.decode()', actionType: 'null_guard' },
    { step: 3, description: 'Raise AuthenticationError instead of returning None on PyJWTError', actionType: 'exception_raise' },
    { step: 4, description: 'Verify caller in auth.py receives clean 401 exception instead of unhandled 500', actionType: 'caller_update' },
  ],
  safety: {
    isValid: true,
    syntaxValid: true,
    astPassed: true,
    secretScanPassed: true,
    scopeVerified: true,
    notes: [
      'Git unified diff hunk syntax validated',
      'Python AST parse succeeded without syntax errors',
      'Secret Shield scanned: 0 credentials or JWT secrets found in patch',
      'Scope verified: strictly 1 culprit file modified (app/auth/login.py)',
      '.env, requirements.txt, and migration folders untouched',
    ],
  },
  risk: {
    level: 'HIGH',
    score: 82,
    isSensitiveModule: true,
    linesChanged: 8,
    reasons: [
      'Authentication module (app/auth/login.py) modified',
      'Exception contract modified from None to AuthenticationError',
      'Low line churn (+6, -2 lines)',
    ],
  },
  rollback: {
    gitApplyReverse: 'git apply -R repair.patch',
    gitRevert: 'git revert HEAD --no-edit',
    hasDatabaseCaution: false,
    steps: [
      'Run: git apply -R repair.patch to invert code modifications',
      'Or run: git revert HEAD if already committed to branch',
      'Execute: pytest backend/tests/test_auth.py to verify regression resolution',
      'No database migrations were executed; schema rollback not required',
    ],
  },
  status: 'proposed',
  createdAt: '2026-09-27T09:14:30Z',
}
