import React, { useState } from 'react'
import {
  Download,
  FileCode,
  FileText,
  Copy,
  Check,
  Share2,
  ShieldCheck,
} from 'lucide-react'
import { useRepairStore, useRootCauseStore, useComparisonStore } from '../../store'
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/Card'
import { Badge } from '../../components/ui/Badge'
import { Button } from '../../components/ui/Button'
import { SectionHeader } from '../../components/ui/SectionHeader'
import './ExportCenter.css'

export const ExportCenter: React.FC = () => {
  const { repair } = useRepairStore()
  const { report } = useRootCauseStore()
  const { summary } = useComparisonStore()
  const [copiedPrSummary, setCopiedPrSummary] = useState(false)
  const [copiedJson, setCopiedJson] = useState(false)

  const prMarkdownSummary = `## IBM Bob Repair Summary

### Root Cause
\`${repair.targetFunction}()\` returned \`None\` for invalid or expired JWT tokens, causing an unhandled \`500 Internal Server Error\` during downstream role validation.

### Proposed Fix
* Added explicit defensive null check in \`${repair.targetFile}\`.
* Raised \`AuthenticationError\` instead of returning \`None\`.
* Caller contract preserved.

### Operational Risk
**${repair.risk.level}** — ${repair.risk.reasons.join(', ')}

### Safety & Pre-flight Verification
* ✅ Python AST Syntax Verification: PASSED
* ✅ Secret Shield Scan: PASSED (0 credentials leaked)
* ✅ Patch Scope: STRICTLY culprit file only (\`${repair.targetFile}\`)

### Rollback Plan
\`\`\`bash
${repair.rollback.gitApplyReverse}
${repair.rollback.gitRevert}
\`\`\`

*Report generated by IBM Bob 2.0 autonomous repair engine.*`

  const handleCopyPrSummary = () => {
    navigator.clipboard.writeText(prMarkdownSummary)
    setCopiedPrSummary(true)
    setTimeout(() => setCopiedPrSummary(false), 2000)
  }

  const handleCopyJson = () => {
    const fullAudit = {
      comparison: summary,
      rootCause: report,
      repair,
      exportedAt: new Date().toISOString(),
    }
    navigator.clipboard.writeText(JSON.stringify(fullAudit, null, 2))
    setCopiedJson(true)
    setTimeout(() => setCopiedJson(false), 2000)
  }

  const handleDownloadPatch = () => {
    const blob = new Blob([repair.patchContent], { type: 'text/x-diff' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `IBM-Bob-${repair.targetFunction}.patch`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleDownloadMarkdownReport = () => {
    const blob = new Blob([prMarkdownSummary], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `IBM-Bob-PR-Summary.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="sd-export-center animate-fade-in">
      <SectionHeader
        title="Artifact & Evidence Export Center"
        subtitle="Export git-compatible patches, GitHub Pull Request descriptions, and comprehensive JSON/Markdown audits for peer review and CI/CD pipelines."
        icon={<Download size={20} />}
      />

      <div className="sd-export-cards-grid">
        {/* Card 1: Git Patch File */}
        <Card variant="glass" className="sd-export-item-card">
          <CardHeader>
            <CardTitle>
              <FileCode size={16} className="text-cyan" /> Unified Git Patch (.patch)
            </CardTitle>
            <Badge severity="INFO" size="sm">GIT COMPATIBLE</Badge>
          </CardHeader>
          <CardContent>
            <p className="sd-export-card-desc">
              Standalone unified diff file ready for <code>git apply</code> or <code>git am</code>. Includes commit headers and AST validated hunk indexes.
            </p>
            <Button
              variant="cyan"
              size="sm"
              icon={<Download size={14} />}
              onClick={handleDownloadPatch}
              className="sd-export-btn"
            >
              Download .patch
            </Button>
          </CardContent>
        </Card>

        {/* Card 2: GitHub PR Summary */}
        <Card variant="glass" className="sd-export-item-card">
          <CardHeader>
            <CardTitle>
              <FileText size={16} className="text-success" /> GitHub PR Description
            </CardTitle>
            <Badge severity="SUCCESS" size="sm">MARKDOWN</Badge>
          </CardHeader>
          <CardContent>
            <p className="sd-export-card-desc">
              Formatted Markdown description ready to paste into GitHub/GitLab Pull Requests with root cause summary, risk tier, and rollback instructions.
            </p>
            <div className="sd-export-btn-group">
              <Button
                variant="outline"
                size="sm"
                icon={copiedPrSummary ? <Check size={14} /> : <Copy size={14} />}
                onClick={handleCopyPrSummary}
              >
                {copiedPrSummary ? 'Copied Markdown!' : 'Copy PR Summary'}
              </Button>
              <Button
                variant="secondary"
                size="sm"
                icon={<Download size={14} />}
                onClick={handleDownloadMarkdownReport}
              >
                Save .md
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Card 3: Full Audit JSON */}
        <Card variant="glass" className="sd-export-item-card">
          <CardHeader>
            <CardTitle>
              <Share2 size={16} className="text-primary" /> Comprehensive Audit (JSON)
            </CardTitle>
            <Badge severity="LOW" size="sm">MACHINE READABLE</Badge>
          </CardHeader>
          <CardContent>
            <p className="sd-export-card-desc">
              Complete machine-readable JSON structure containing raw Playwright runtime events, comparator divergence index, causal graph, and patch metadata.
            </p>
            <Button
              variant="outline"
              size="sm"
              icon={copiedJson ? <Check size={14} /> : <Copy size={14} />}
              onClick={handleCopyJson}
              className="sd-export-btn"
            >
              {copiedJson ? 'Copied JSON!' : 'Copy Full Audit JSON'}
            </Button>
          </CardContent>
        </Card>
      </div>

      {/* Live Preview Box of GitHub PR Markdown */}
      <Card className="sd-export-preview-card">
        <CardHeader>
          <CardTitle>
            <FileText size={16} /> GitHub Pull Request Preview
          </CardTitle>
          <span className="sd-export-shield-badge">
            <ShieldCheck size={13} /> Masked Secrets Verified
          </span>
        </CardHeader>
        <CardContent>
          <pre className="sd-export-markdown-preview">
            {prMarkdownSummary}
          </pre>
        </CardContent>
      </Card>
    </div>
  )
}
